# Generated by Django 3.0.7 on 2020-06-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=200)),
                ('sales_organic', models.CharField(default='', max_length=200)),
                ('sales_ppc', models.CharField(default='', max_length=200)),
                ('units_organic', models.CharField(default='', max_length=200)),
                ('units_ppc', models.CharField(default='', max_length=200)),
                ('orders', models.CharField(default='', max_length=200)),
                ('refunds', models.CharField(default='', max_length=200)),
                ('promo_value', models.CharField(default='', max_length=200)),
                ('sponsored_products', models.CharField(default='', max_length=200)),
                ('headline_search', models.CharField(default='', max_length=200)),
                ('giftwrap', models.CharField(default='', max_length=200)),
                ('shipping', models.CharField(default='', max_length=200)),
                ('refund_cost', models.CharField(default='', max_length=200)),
                ('commission', models.CharField(default='', max_length=200)),
                ('compensated_clawback', models.CharField(default='', max_length=200)),
                ('coupon_redemption_fee', models.CharField(default='', max_length=200)),
                ('fba_inbound_transportation_fee', models.CharField(default='', max_length=200)),
                ('fba_per_unit_fulfillment_fee', models.CharField(default='', max_length=200)),
                ('fba_removal_fee', models.CharField(default='', max_length=200)),
                ('fba_transportation_fee', models.CharField(default='', max_length=200)),
                ('reversal_reimbursement', models.CharField(default='', max_length=200)),
                ('sales_tax_collection_fee', models.CharField(default='', max_length=200)),
                ('variable_closing_fee', models.CharField(default='', max_length=200)),
                ('warehouse_damage', models.CharField(default='', max_length=200)),
                ('warehouse_lost', models.CharField(default='', max_length=200)),
                ('estimated_payout', models.CharField(default='', max_length=200)),
                ('product_cost_sales', models.CharField(default='', max_length=200)),
                ('product_cost_refunds', models.CharField(default='', max_length=200)),
                ('product_cost_unsellable_refunds', models.CharField(default='', max_length=200)),
                ('product_cost_non_amazon', models.CharField(default='', max_length=200)),
                ('product_cost_missing_from_inbound', models.CharField(default='', max_length=200)),
                ('gross_profit', models.CharField(default='', max_length=200)),
                ('net_profit', models.CharField(default='', max_length=200)),
                ('margin', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
